services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=brewerydb'
      - 'POSTGRES_PASSWORD=DB_PASSWORD'
      - 'POSTGRES_USER=DB_USERNAME'
    ports:
      - '5432'
